function addSwingAnnotation(ax, t1, t2, label)
    axPos = ax.Position;
    xlims = ax.XLim;
    x1 = (t1 - xlims(1)) / diff(xlims);
    x2 = (t2 - xlims(1)) / diff(xlims);
    left = axPos(1) + axPos(3) * x1;
    width = axPos(3) * (x2 - x1);
    if contains(label, 'contra', 'IgnoreCase', true)
        annotation('textbox', [left, axPos(2)-0.01, width, 0.022], ...
        'String', label, 'HorizontalAlignment', 'center', ...
        'EdgeColor', 'black','BackgroundColor', 'black',...
        'FontSize', 11, 'Color','white',...
        'VerticalAlignment', 'middle');
    else
         annotation('textbox', [left, axPos(2)-0.01, width, 0.02], ...
        'String', label, 'HorizontalAlignment', 'center', ...
        'EdgeColor', 'white','BackgroundColor', 'white',...
        'FontSize', 11, 'Color','black',...
        'VerticalAlignment', 'middle');
    end
end